services:
  spark-master:
        image: bitnami/spark:3.4.0
        environment:
          - SPARK_MODE=master
          - SPARK_MASTER_PORT=7077
          - SPARK_MASTER_WEBUI_PORT=4040
        ports:
          - "4040:4040"
          - "7077:7077"
        volumes:
          - /Users/anoopm/Documents/Local_Folder:/mnt
          - "/Users/anoopm/Library/CloudStorage/OneDrive-Personal/Cloud Documents:/data"
          - ./dags:/opt/airflow/dags
          - ./Spark-Config:/opt/airflow/config

  spark-worker:
        image: bitnami/spark:3.4.0
        environment:
          - SPARK_MODE=worker
          - SPARK_MASTER_URL=spark://spark-master:7077
          - SPARK_WORKER_WEBUI_PORT=8081
        depends_on:
          - spark-master
        volumes:
          - /Users/anoopm/Documents/Local_Folder:/mnt
          - "/Users/anoopm/Library/CloudStorage/OneDrive-Personal/Cloud Documents:/data"
          - ./dags:/opt/airflow/dags
          - ./Spark-Config:/opt/airflow/config
        ports:
          - "8081:8081"
          - "7337:7337"
